declare const process: {
  env: {
    EXPO_PUBLIC_ADMOB_BANNER_ANDROID?: string;
    EXPO_PUBLIC_ADMOB_INTERSTITIAL_ANDROID?: string;
    EXPO_PUBLIC_ADMOB_REWARDED_ANDROID?: string;
    EXPO_PUBLIC_DISABLE_ADMOB?: string;
    EXPO_PUBLIC_ADMOB_BANNER_IOS?: string;
    EXPO_PUBLIC_ADMOB_INTERSTITIAL_IOS?: string;
    EXPO_PUBLIC_ADMOB_REWARDED_IOS?: string;
  };
};
